# Generated by Django 4.1.2 on 2022-10-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_profile_linkedin_url_profile_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
